title: Bokerh's blog
description: Some memos about linux operation
theme: just-the-docs

url: https://bokerh.github.io
mermaid:
  version: "11.4.1"

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

nav_enabled: true
heading_anchors: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
