title: Bokerh's blog
description: Some memos about linux operation
theme: just-the-docs

url: https://bokerh.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
